# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
#2 containers db and rblog

version: '3.7'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: always 

  rblog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RBLOG_PORT}:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure 

volumes:
  db_data:
    driver: local

