# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.7'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: thomas
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - list_network

  rblog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: 'postgres://thomas:admin@db:5432/blog'
      ROCKET_ADDRESS: '0.0.0.0'
    depends_on:
      - db
    networks:
      - list_network

volumes:
  db_data:
    driver: local

networks:
  list_network:
