# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.

version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=prod
    volumes:
      - .:/usr/src/restaurant-website

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/src/restaurant-website/public:ro
    depends_on:
      - php
