# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: "3"

services:
  website:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nodeclient
    ports:
      - "3000:4173"
    networks:
      - makeMeWatchNetwork
  apiMakeMeWatch:
    image: nodeserver
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - makeMeWatchNetwork

networks:
  makeMeWatchNetwork:
    driver: bridge
