# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: "3"

services:
  website:
    image: nodeclient
    ports:
      - "4173:4173"
      - "80:80"
    networks:
      - makeMeWatchNetwork
  apiMakeMeWatch:
    image: nodeserver
    ports:
      - "3000:3000"
    networks:
      - makeMeWatchNetwork

networks:
  makeMeWatchNetwork:
    driver: bridge
