# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: "3"

services:
  website:
    image: nodeclient
    ports:
      - "3000:4173"
    networks:
      - makeMeWatchNetwork
  apiMakeMeWatch:
    image: nodeserver
    networks:
      - makeMeWatchNetwork

networks:
  makeMeWatchNetwork:
    driver: bridge
