# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: "3"

services:
  apiMakeMeWatch:
    image: nodeserver
    build:
      context: ./server
      dockerfile: Dockerfile

  website:
    image: nodeclient
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 0:3000
